name: API Lojao

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#defaults:
#  run:
#    working-directory: ./Services

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
#      working-directory: ./Services
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: AWS CLI
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#    - name: Package Lambda
#      run: dotnet lambda package
    - name: Deploy to Lambda
#      working-directory: ./Services/ApiServices
      run: dotnet lambda deploy-serverless --stack-name nmlAPI --s3-bucket lojaodosdezreaisapi
#      run: dotnet lambda delete-serverless --stack-name CustomRuntimeNET5API --s3-bucket lojaodosdezreaisapi